### ISSUE TITLE
关于数据集

### ISSUE THREAD

**Issue by czh17** [JBoRu/UniKGQA#1]
作者您好，
     非常新颖且有价值的工作~！我注意到您在README中提到两处数据集的下载，但是地址都失效了，您是否能重新提供一下数据集的下载地址呢，非常感谢，祝好~！

**Comment by JBoRu** [comment]
您好，
感谢关注，论文目前正处于审稿中，我们将在审稿结束后，放出所有相关的预处理数据和模型checkpoint，您可以持续关注！
